# fly.toml app configuration file generated for website-hmik on 2023-06-21T17:19:03+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "website-hmik"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_NAME="website-hmik"
  APP_ENV="local"
  APP_KEY=""
  APP_DEBUG="true"
  APP_URL="https://website-hmik.fly.dev/"

  LOG_CHANNEL="stack"
  LOG_LEVEL="debug"

  DB_CONNECTION="mysql"
  DB_HOST="hmik-sgp1-52088-do-user-14154237-0.b.db.ondigitalocean.com"
  DB_PORT="25060"
  DB_DATABASE="db_hmik"
  DB_USERNAME="doadmin"

  BROADCAST_DRIVER="log"
  CACHE_DRIVER="file"
  FILESYSTEM_DRIVER="local"
  QUEUE_CONNECTION="sync"
  SESSION_DRIVER="file"
  SESSION_LIFETIME="120"

  MEMCACHED_HOST="127.0.0.1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
